### ISSUE TITLE
Not enough readme

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [VTCAKAVSMoACE/Laura#1]

**Comment by VTCAKAVSMoACE** [comment]
I'm working on it - I've had little to no time to work on this so far, when school ends, I'll be able to make MOAR README. Apologies. In the meantime, [here's a doc on what the class header byte code looks like so far](https://docs.google.com/spreadsheets/d/1p_9_aGt5hycmzt9bIWhyvLYiEJXzP9dTwA4au1gG5uM/edit#gid=0).

**Comment by VTCAKAVSMoACE** [comment]
Fixed. I think.
